/**
 * Spofity API
 * Spotify API description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.arpadfodor.android.songquiz.model.api.dataclasses

/**
 * 
 * @param album 
 * @param artists 
 * @param available_markets
 * @param disc_number
 * @param duration_ms
 * @param explicit 
 * @param external_ids
 * @param external_urls
 * @param href 
 * @param id 
 * @param name 
 * @param popularity 
 * @param preview_url
 * @param track_number
 * @param type 
 * @param uri 
 */
data class ApiTrack (
    val album: ApiAlbum? = null,
    val artists: kotlin.Array<ApiArtist>,
    val available_markets: kotlin.Array<kotlin.String>? = null,
    val disc_number: kotlin.Int? = null,
    val duration_ms: kotlin.Int,
    val explicit: kotlin.Boolean? = null,
    val external_ids: ApiTrackExternalIds? = null,
    val external_urls: PlaylistExternalUrls? = null,
    val href: kotlin.String? = null,
    val id: kotlin.String,
    val name: kotlin.String,
    val popularity: kotlin.Int? = null,
    val preview_url: kotlin.String? = null,
    val track_number: kotlin.Int? = null,
    val type: kotlin.String? = null,
    val uri: kotlin.String? = null
)

/**
 *
 * @param isrc
 */
data class ApiTrackExternalIds (
    val isrc: kotlin.String? = null
)

/**
 *
 * @param album_type
 * @param available_markets
 * @param external_urls
 * @param href
 * @param id
 * @param images
 * @param name
 * @param type
 * @param uri
 */
data class ApiAlbum (
    val album_type: kotlin.String? = null,
    val available_markets: kotlin.Array<kotlin.String>? = null,
    val external_urls: PlaylistExternalUrls? = null,
    val href: kotlin.String? = null,
    val id: kotlin.String,
    val images: kotlin.Array<ApiAlbumImages>? = null,
    val name: kotlin.String,
    val type: kotlin.String? = null,
    val uri: kotlin.String? = null
)

/**
 *
 * @param height
 * @param url
 * @param width
 */
data class ApiAlbumImages (
    val height: kotlin.Int,
    val url: kotlin.String,
    val width: kotlin.Int
)

/**
 *
 * @param external_urls
 * @param href
 * @param id
 * @param name
 * @param type
 * @param uri
 */
data class ApiArtist (
    val external_urls: PlaylistExternalUrls? = null,
    val href: kotlin.String? = null,
    val id: kotlin.String,
    val name: kotlin.String,
    val type: kotlin.String? = null,
    val uri: kotlin.String? = null
)