/**
 * Spofity API
 * Spotify API description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.arpadfodor.android.songquiz.model.api.dataclasses

/**
 * 
 * @param access_token
 * @param token_type
 * @param expires_in
 */
data class ApiToken (
    val access_token: kotlin.String,
    val token_type: kotlin.String? = null,
    val expires_in: kotlin.Int? = null
)