/**
 * Spofity API
 * Spotify API description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.arpadfodor.android.songquiz.model.api.dataclasses

/**
 * 
 * @param status 
 * @param message 
 */
data class ErrorDTO (
    val status: Int? = null,
    val message: String? = null
)