sudo: required
language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-30.0.3
    - android-30
    - android-22
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-24

env:
  global:
    - MALLOC_ARENA_MAX=2

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-30"

before_script:
  - cd application
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean build
  - ./gradlew test
  - ./gradlew build check

deploy:
  provider: releases
  apikey: $GITHUB_KEY
  file: app/build/outputs/apk/release/app-release.apk
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
    - arpadfodor01@gmail.com
    on_success: always
    on_failure: always
